#url: http://puppet-br.org
url: https://aeciopires.github.io/puppet-br/

name: Puppet-BR - Comunidade brasileira de usuários Puppet

description: Site da comunidade Puppet-BR

logo: /images/puppet-users-br.png 

exclude:
  - README.md
  - .gitignore

theme: jekyll-theme-cayman
